kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name:
networking:
  apiServerPort: 16443
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080
        protocol: TCP
      - containerPort: 443
        hostPort: 8081
        protocol: TCP
      - hostPort: 30080
        listenAddress: "0.0.0.0"
        containerPort: 30080
        protocol: TCP
      - hostPort: 30443
        listenAddress: "0.0.0.0"
        containerPort: 30443
        protocol: TCP
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "master=true"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "worker=true"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "worker=true"
containerdConfigPatches:
  - "[plugins.\"io.containerd.grpc.v1.cri\".registry.mirrors.\"10.21.84.254:8443\"]\n  endpoint = [\"http://10.21.84.254:8443\"]\n  [plugins.\"io.containerd.grpc.v1.cri\".registry.configs.\"10.21.84.254:8443\".tls]\n  insecure_skip_verify = true "
