apiVersion: v1
kind: Service
metadata:
  name: library-service
spec:
  selector:
    app: library
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
    - name: pgadmin
      protocol: TCP
      port: 5050
      targetPort: 80
    - name: webserver
      protocol: TCP
      port: 443
      targetPort: 443
    - name: backend
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: LoadBalancer
