- name: Update Apt Cache
  apt:
    update_cache: yes
- name: Install Apache2
  apt:
    name: apache2
    state: present
- name: Apache is running and enabled
  service:
    name: apache2
    state: started
    enabled: yes
- name: Install Git
  apt:
    name: git
    state: present
- name: Remove /var/www/html and all contents
  command: rm -rf /var/www/html/
- name: Clone web-sample-6 repository
  git:
    repo: https://github.com/rm77/web-sample-6.git
    dest: /var/www/html
    update: yes
- name: permissions for /var/www/html
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
    recurse: yes
- name: Allow HTTP traffic on port 80 (UFW)
  ufw:
    rule: allow
    port: 80
    proto: tcp
